# Generated by Django 5.2.1 on 2025-06-05 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('video', models.FileField(upload_to='clips/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='choices/')),
                ('from_clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='eden.clip')),
                ('to_clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_choices', to='eden.clip')),
            ],
        ),
    ]
