# Generated by Django 5.2.1 on 2025-06-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order to display choices'),
        ),
        migrations.AddField(
            model_name='clip',
            name='audio_prompt',
            field=models.FileField(blank=True, null=True, upload_to='audio_prompts/'),
        ),
        migrations.AddField(
            model_name='clip',
            name='extra_notes',
            field=models.TextField(blank=True, help_text='Internal notes or script directions'),
        ),
        migrations.AddField(
            model_name='clip',
            name='prompt_time',
            field=models.FloatField(default=0.0, help_text='Time (in seconds) to show choices or prompt'),
        ),
        migrations.AlterField(
            model_name='clip',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
