# Generated by Django 4.2.24 on 2025-09-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0002_choice_order_clip_audio_prompt_clip_extra_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='is_start_clip',
            field=models.BooleanField(default=False, help_text='Set to True for the very first clip of the film.'),
        ),
    ]
