# Generated by Django 4.2.24 on 2025-09-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0003_clip_is_start_clip'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='transcript',
            field=models.TextField(blank=True, help_text="Auto-generated transcript of the clip's audio."),
        ),
    ]
