# Generated by Django 5.2.1 on 2025-07-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclip',
            name='edit_end',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userclip',
            name='edit_start',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
