# Generated by Django 5.2.1 on 2025-07-01 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='user_clips/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='user_thumbnails/')),
                ('narrative', models.TextField(blank=True)),
                ('prompt_time', models.FloatField(default=0)),
                ('audio_prompt', models.FileField(blank=True, upload_to='user_audio_prompts/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('from_clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices_from', to='user.userclip')),
                ('to_clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices_to', to='user.userclip')),
            ],
        ),
        migrations.CreateModel(
            name='UserFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userclip',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='user.userfilm'),
        ),
    ]
